Set CONDA_BUILD_SYSROOT and use the macOS 10.9 SDK
The SDK has to be downloaded from a GitHub repository because Apple
no longer distribute it. This is basically what conda-forge do in
their feedstocks.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -22,6 +22,20 @@ install:
     elif [[ "$CONDA_ARCH" == "linux_x86" ]]; then
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86.sh -O miniconda.sh;
     elif [[ "$CONDA_ARCH" == "osx_x64" ]]; then
+      export MACOSX_DEPLOYMENT_TARGET="10.9"
+      export CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
+      curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
+      tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(dirname "$CONDA_BUILD_SYSROOT")"
+      # set minimum sdk version to our target
+      plutil -replace MinimumSDKVersion -string ${MACOSX_DEPLOYMENT_TARGET} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
+      plutil -replace DTSDKName -string macosx${MACOSX_DEPLOYMENT_TARGET}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
+
+      if [ -d "${CONDA_BUILD_SYSROOT}" ]; then
+          echo "Found CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+      else
+          echo "Missing CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+          exit 1
+      fi
       curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
     fi
   - bash miniconda.sh -b -p $HOME/miniconda
@@ -49,3 +63,9 @@ matrix:
       env: BUILD_ARCH="x64"
     - os: osx
       env: BUILD_ARCH="x64"
+    - os: linux
+      env: BUILD_ARCH="x86" MATLAB_BUILD=1
+    - os: linux
+      env: BUILD_ARCH="x64" MATLAB_BUILD=1
+    - os: osx
+      env: BUILD_ARCH="x64" MATLAB_BUILD=1
