Check that the macOS SDK is properly found on Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,6 +27,12 @@ install:
       # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/53c72da/recipe/run_conda_forge_build_setup_osx#L22
       export MACOSX_DEPLOYMENT_TARGET="10.9"
       export CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
+      if [ -d "${CONDA_BUILD_SYSROOT}" ]; then
+          echo "Found CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+      else
+          echo "Missing CONDA_BUILD_SYSROOT: ${CONDA_BUILD_SYSROOT}"
+          exit 1
+      fi
       curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
     fi
   - bash miniconda.sh -b -p $HOME/miniconda
